[meta_properties]
id = "b4c7e1a2096f835d"
asset_kind = "Animation"

[asset_properties]
frame_size = [25, 20]
frame_len = 6
duration = [0.075, 0.075, 0.075, 0.075, 0.075, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 12.0
