#!/usr/bin/env python3
"""Build predeclared Font Lab assets from one or more untouched TTF/OTF files.

Metadata belongs to a game asset, so runtime UI can only choose variants built
in advance. This tool emits one copied font and one metadata file per variant,
plus a GML registry consumed by FontChoices.gml.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import tomllib
from pathlib import Path


def asset_id(name: str) -> str:
    """Stable 16-hex asset id, avoiding manual ID bookkeeping."""
    return hashlib.sha256(("font-lab:" + name).encode("utf-8")).hexdigest()[:16]


def gml_quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def build(root: Path, config_path: Path) -> None:
    with config_path.open("rb") as handle:
        config = tomllib.load(handle)

    fonts_dir = root / "fonts"
    generated_gml = root / "gml" / "FontLabVariants.generated.gml"
    fonts_dir.mkdir(parents=True, exist_ok=True)
    generated_gml.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Generated by tools/build_font_lab_variants.py. Do not hand-edit.",
        "function fc_lab_registry() {",
        "    static _registry = [",
    ]

    seen_assets: set[str] = set()
    for family in config.get("font", []):
        family_id = family["id"]
        source = (root / family["source"]).resolve()
        if not source.is_file():
            raise FileNotFoundError(f"Missing source font: {source}")
        suffix = source.suffix.lower()
        if suffix not in {".ttf", ".otf"}:
            raise ValueError(f"Unsupported font extension for {source.name}: {suffix}")

        languages = ", ".join(gml_quote(code) for code in family.get("languages", []))
        lines.append("        {")
        lines.append(f"            id: {gml_quote(family_id)}, label: {gml_quote(family['label'])}, languages: [{languages}],")
        lines.append("            variants: [")

        for variant in family.get("variant", []):
            variant_id = variant["id"]
            asset_name = f"fnt_font_lab_{family_id}_{variant_id}"
            if asset_name in seen_assets:
                raise ValueError(f"Duplicate generated asset name: {asset_name}")
            seen_assets.add(asset_name)

            target_font = fonts_dir / f"{asset_name}{suffix}"
            target_meta = fonts_dir / f"{asset_name}.meta.toml"
            shutil.copyfile(source, target_font)
            target_meta.write_text(
                "[meta_properties]\n"
                f"id = \"{asset_id(asset_name)}\"\n"
                "asset_kind = \"Font\"\n\n"
                "[asset_properties]\n"
                f"minimum_expected_size = {int(variant['size'])}\n"
                f"minimum_expected_line_height = {int(variant['line_height'])}\n"
                f"allow_shading = {'true' if variant['allow_shading'] else 'false'}\n",
                encoding="utf-8",
            )
            targets = ", ".join(gml_quote(target) for target in variant.get("targets", ["all", "standard", "popup_description", "textbox"]))
            # Emit the field for every variant. Saved selections from an older
            # build may point at a variant that did not have an override list;
            # the GML registry must not depend on an optional struct field.
            variant_languages = variant.get("languages", family.get("languages", []))
            languages = ", ".join(gml_quote(code) for code in variant_languages)
            language_field = f"languages: [{languages}], "
            lines.append(
                "                { "
                f"id: {gml_quote(variant_id)}, "
                f"asset: {gml_quote(asset_name)}, size: {int(variant['size'])}, "
                f"line_height: {int(variant['line_height'])}, "
                f"allow_shading: {'true' if variant['allow_shading'] else 'false'}, "
                f"targets: [{targets}], {language_field}"
                "},"
            )

        lines.append("            ],")
        lines.append("        },")

    lines.extend(["    ];", "    return _registry;", "}", ""])
    generated_gml.write_text("\n".join(lines), encoding="utf-8")
    # Remove only assets this generator owns. This keeps retired variants out
    # of the packaged mod while preserving hand-authored source-font assets.
    for stale in fonts_dir.glob("fnt_font_lab_*.*"):
        stale_asset = stale.name.removesuffix(".meta.toml") if stale.name.endswith(".meta.toml") else stale.stem
        if stale_asset not in seen_assets:
            stale.unlink()
    print(f"Generated {len(seen_assets)} Font Lab assets and {generated_gml.relative_to(root)}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--config", type=Path, default=None)
    args = parser.parse_args()
    root = args.root.resolve()
    config = args.config.resolve() if args.config else root / "font-lab-variants.toml"
    build(root, config)


if __name__ == "__main__":
    main()
