// Generated by tools/build_font_lab_variants.py. Do not hand-edit.
function fc_lab_registry() {
    static _registry = [
        {
            id: "ibm_plex", label: "IBM Plex", languages: ["eng", "bul", "fra", "spa", "rus", "por", "pol"],
            variants: [
                { id: "compact_shaded", asset: "fnt_font_lab_ibm_plex_compact_shaded", size: 14, line_height: 12, allow_shading: true, targets: ["all", "standard", "popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por", "tur"], },
                { id: "standard_shaded", asset: "fnt_font_lab_ibm_plex_standard_shaded", size: 17, line_height: 13, allow_shading: true, targets: ["all", "standard", "popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "por", "pol", "tur"], },
                { id: "tall_shaded", asset: "fnt_font_lab_ibm_plex_tall_shaded", size: 19, line_height: 14, allow_shading: true, targets: ["popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por", "tur"], },
                { id: "standard_flat", asset: "fnt_font_lab_ibm_plex_standard_flat", size: 17, line_height: 13, allow_shading: false, targets: ["all", "standard", "popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "por", "pol", "tur"], },
            ],
        },
        {
            id: "sofia_condensed", label: "Sofia Condensed", languages: ["bul", "rus"],
            variants: [
                { id: "standard_shaded", asset: "fnt_font_lab_sofia_condensed_standard_shaded", size: 17, line_height: 13, allow_shading: true, targets: ["all", "standard", "popup_description", "textbox"], languages: ["bul", "rus"], },
                { id: "standard_flat", asset: "fnt_font_lab_sofia_condensed_standard_flat", size: 17, line_height: 13, allow_shading: false, targets: ["all", "standard", "popup_description", "textbox"], languages: ["bul", "rus"], },
                { id: "tall_shaded", asset: "fnt_font_lab_sofia_condensed_tall_shaded", size: 19, line_height: 14, allow_shading: true, targets: ["popup_description", "textbox"], languages: ["bul", "rus"], },
            ],
        },
        {
            id: "monomakh", label: "Monomakh", languages: ["eng", "bul", "fra", "spa", "rus", "por", "tur"],
            variants: [
                { id: "standard_shaded", asset: "fnt_font_lab_monomakh_standard_shaded", size: 17, line_height: 13, allow_shading: true, targets: ["all", "standard", "popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por", "tur"], },
                { id: "standard_flat", asset: "fnt_font_lab_monomakh_standard_flat", size: 17, line_height: 13, allow_shading: false, targets: ["all", "standard", "popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por", "tur"], },
                { id: "tall_shaded", asset: "fnt_font_lab_monomakh_tall_shaded", size: 19, line_height: 14, allow_shading: true, targets: ["popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por", "tur"], },
            ],
        },
        {
            id: "ponomar", label: "Ponomar", languages: ["eng", "bul", "fra", "spa", "rus", "por"],
            variants: [
                { id: "standard_shaded", asset: "fnt_font_lab_ponomar_standard_shaded", size: 17, line_height: 13, allow_shading: true, targets: ["all", "standard", "popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por"], },
                { id: "standard_flat", asset: "fnt_font_lab_ponomar_standard_flat", size: 17, line_height: 13, allow_shading: false, targets: ["all", "standard", "popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por"], },
                { id: "tall_shaded", asset: "fnt_font_lab_ponomar_tall_shaded", size: 19, line_height: 14, allow_shading: true, targets: ["popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por"], },
            ],
        },
        {
            id: "triodion", label: "Triodion", languages: ["eng", "bul", "fra", "spa", "rus", "por"],
            variants: [
                { id: "standard_shaded", asset: "fnt_font_lab_triodion_standard_shaded", size: 17, line_height: 13, allow_shading: true, targets: ["all", "standard", "popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por"], },
                { id: "standard_flat", asset: "fnt_font_lab_triodion_standard_flat", size: 17, line_height: 13, allow_shading: false, targets: ["all", "standard", "popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por"], },
                { id: "tall_shaded", asset: "fnt_font_lab_triodion_tall_shaded", size: 19, line_height: 14, allow_shading: true, targets: ["popup_description", "textbox"], languages: ["eng", "bul", "fra", "spa", "rus", "por"], },
            ],
        },
        {
            id: "sofia_extra_condensed", label: "Sofia Extra Condensed", languages: ["bul", "rus"],
            variants: [
                { id: "standard_shaded", asset: "fnt_font_lab_sofia_extra_condensed_standard_shaded", size: 17, line_height: 13, allow_shading: true, targets: ["all", "standard", "popup_description", "textbox"], languages: ["bul", "rus"], },
                { id: "standard_flat", asset: "fnt_font_lab_sofia_extra_condensed_standard_flat", size: 17, line_height: 13, allow_shading: false, targets: ["all", "standard", "popup_description", "textbox"], languages: ["bul", "rus"], },
                { id: "tall_shaded", asset: "fnt_font_lab_sofia_extra_condensed_tall_shaded", size: 19, line_height: 14, allow_shading: true, targets: ["popup_description", "textbox"], languages: ["bul", "rus"], },
            ],
        },
    ];
    return _registry;
}
